[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nauticalminds"
version = "0.0.1"
dependencies = [
    "Flask",
]

[tool.setuptools]
include-package-data = false
