"""init song model

Revision ID: 5698cb73d04d
Revises: 
Create Date: 2020-05-31 20:32:55.629950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5698cb73d04d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('absolute_file_path', sa.String(length=128), nullable=True),
        sa.Column('artist', sa.String(length=128), nullable=True),
        sa.Column('album', sa.String(length=128), nullable=True),
        sa.Column('name', sa.String(length=128), nullable=True),
        sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('plays', sa.Integer(), nullable=True),
        sa.Column('pauses', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    # ### end Alembic commands ###
