"""added created field for fan

Revision ID: 9da4d419e600
Revises: e61881496987
Create Date: 2019-03-18 21:10:03.720234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da4d419e600'
down_revision = 'e61881496987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fan', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fan', 'created')
    # ### end Alembic commands ###
