"""inital prod migration

Revision ID: d7685442b112
Revises: 
Create Date: 2020-08-06 03:09:54.785916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7685442b112'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('absolute_file_path', sa.String(length=128), nullable=True),
        sa.Column('artist', sa.String(length=128), nullable=True),
        sa.Column('album', sa.String(length=128), nullable=True),
        sa.Column('name', sa.String(length=128), nullable=True),
        sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('plays', sa.Integer(), nullable=True),
        sa.Column('pauses', sa.Integer(), nullable=True),
        sa.Column('downloads', sa.Integer(), nullable=True),
        sa.Column('title', sa.String(length=256), nullable=True),
        sa.Column('download_url', sa.String(length=256), nullable=True),
        sa.Column('stream_url', sa.String(length=256), nullable=True),
        sa.Column('duration', postgresql.DOUBLE_PRECISION(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=128), nullable=False),
        sa.Column('email_confirmed', sa.Boolean(), nullable=True),
        sa.Column('first_name', sa.String(length=128), nullable=True),
        sa.Column('last_name', sa.String(length=128), nullable=True),
        sa.Column('password_hash', sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('comment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('comment_text', sa.String(length=1000), nullable=True),
        sa.Column('datetime', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('song')
    # ### end Alembic commands ###
